"""init

Revision ID: 059c76cb4585
Revises: 
Create Date: 2022-09-15 21:52:33.184503

"""
from alembic import op
import sqlalchemy as sa
import ormar


# revision identifiers, used by Alembic.
revision = '059c76cb4585'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_types',
    sa.Column('uuid', ormar.fields.sqlalchemy_uuid.CHAR(32), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_document_types_name'), 'document_types', ['name'], unique=True)
    op.create_table('npa_sections',
    sa.Column('uuid', ormar.fields.sqlalchemy_uuid.CHAR(32), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_agencies_of_state_authorities', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('signatory_authorities',
    sa.Column('uuid', ormar.fields.sqlalchemy_uuid.CHAR(32), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('npa_documents',
    sa.Column('uuid', ormar.fields.sqlalchemy_uuid.CHAR(32), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('complex_name', sa.String(length=5000), nullable=False),
    sa.Column('name', sa.String(length=5000), nullable=False),
    sa.Column('document_date', sa.Date(), nullable=False),
    sa.Column('publish_date_short', sa.DateTime(), nullable=False),
    sa.Column('document_type', sa.Integer(), nullable=False),
    sa.Column('eo_number', sa.String(length=16), nullable=False),
    sa.Column('has_pdf', sa.Boolean(), nullable=False),
    sa.Column('number', sa.String(length=128), nullable=True),
    sa.Column('signatory_authority', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_type'], ['document_types.id'], name='fk_npa_documents_document_types_id_document_type'),
    sa.ForeignKeyConstraint(['signatory_authority'], ['signatory_authorities.id'], name='fk_npa_documents_signatory_authorities_id_signatory_authority'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('complex_name'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('npa_subsections',
    sa.Column('uuid', ormar.fields.sqlalchemy_uuid.CHAR(32), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_agencies_of_state_authorities', sa.Boolean(), nullable=False),
    sa.Column('npa_section', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['npa_section'], ['npa_sections.id'], name='fk_npa_subsections_npa_sections_id_npa_section', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('npa_subsections')
    op.drop_table('npa_documents')
    op.drop_table('signatory_authorities')
    op.drop_table('npa_sections')
    op.drop_index(op.f('ix_document_types_name'), table_name='document_types')
    op.drop_table('document_types')
    # ### end Alembic commands ###
