"""add npa section

Revision ID: 57aafc2c3fff
Revises: 9dcdbff3ff99
Create Date: 2022-09-12 21:34:33.618868

"""
from alembic import op
import sqlalchemy as sa
import ormar


# revision identifiers, used by Alembic.
revision = '57aafc2c3fff'
down_revision = '9dcdbff3ff99'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('npa_subsections',
    sa.Column('uuid', ormar.fields.sqlalchemy_uuid.CHAR(32), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_agencies_of_state_authorities', sa.Boolean(), nullable=False),
    sa.Column('npa_section', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['npa_section'], ['npa_sections.id'], name='fk_npa_subsections_npa_sections_id_npa_section', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_unique_constraint(None, 'document_types', ['id'])
    op.create_unique_constraint(None, 'npa_sections', ['id'])
    op.create_unique_constraint(None, 'signatory_authorities', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'signatory_authorities', type_='unique')
    op.drop_constraint(None, 'npa_sections', type_='unique')
    op.drop_constraint(None, 'document_types', type_='unique')
    op.drop_table('npa_subsections')
    # ### end Alembic commands ###
