"""add npa document

Revision ID: 997b6f201863
Revises: 57aafc2c3fff
Create Date: 2022-09-12 22:36:17.142671

"""
from alembic import op
import sqlalchemy as sa
import ormar


# revision identifiers, used by Alembic.
revision = '997b6f201863'
down_revision = '57aafc2c3fff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('npa_documents',
    sa.Column('uuid', ormar.fields.sqlalchemy_uuid.CHAR(32), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('complex_name', sa.String(length=512), nullable=False),
    sa.Column('document_date', sa.Date(), nullable=False),
    sa.Column('publish_date_short', sa.DateTime(), nullable=False),
    sa.Column('document_type', sa.Integer(), nullable=False),
    sa.Column('eo_number', sa.String(length=16), nullable=False),
    sa.Column('has_pdf', sa.Boolean(), nullable=False),
    sa.Column('number', sa.String(length=128), nullable=False),
    sa.Column('signatory_authority', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_type'], ['document_types.id'], name='fk_npa_documents_document_types_id_document_type'),
    sa.ForeignKeyConstraint(['signatory_authority'], ['signatory_authorities.id'], name='fk_npa_documents_signatory_authorities_id_signatory_authority'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('complex_name'),
    sa.UniqueConstraint('id')
    )
    op.create_unique_constraint(None, 'npa_subsections', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'npa_subsections', type_='unique')
    op.drop_table('npa_documents')
    # ### end Alembic commands ###
