"""nullable document_type

Revision ID: 1b568f025b42
Revises: 059c76cb4585
Create Date: 2022-09-15 22:08:15.449040

"""
from alembic import op
import sqlalchemy as sa
import ormar


# revision identifiers, used by Alembic.
revision = '1b568f025b42'
down_revision = '059c76cb4585'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'document_types', ['id'])
    op.alter_column('npa_documents', 'document_type',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('npa_documents', 'signatory_authority',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(None, 'npa_documents', ['id'])
    op.create_unique_constraint(None, 'npa_sections', ['id'])
    op.create_unique_constraint(None, 'npa_subsections', ['id'])
    op.create_unique_constraint(None, 'signatory_authorities', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'signatory_authorities', type_='unique')
    op.drop_constraint(None, 'npa_subsections', type_='unique')
    op.drop_constraint(None, 'npa_sections', type_='unique')
    op.drop_constraint(None, 'npa_documents', type_='unique')
    op.alter_column('npa_documents', 'signatory_authority',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('npa_documents', 'document_type',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'document_types', type_='unique')
    # ### end Alembic commands ###
