"""add npa document

Revision ID: ccb956606ce0
Revises: 997b6f201863
Create Date: 2022-09-12 22:45:47.984499

"""
from alembic import op
import sqlalchemy as sa
import ormar


# revision identifiers, used by Alembic.
revision = 'ccb956606ce0'
down_revision = '997b6f201863'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('npa_documents', sa.Column('name', sa.String(length=512), nullable=False))
    op.create_unique_constraint(None, 'npa_documents', ['id'])
    op.create_unique_constraint(None, 'npa_documents', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'npa_documents', type_='unique')
    op.drop_constraint(None, 'npa_documents', type_='unique')
    op.drop_column('npa_documents', 'name')
    # ### end Alembic commands ###
