"""corret npa_document model

Revision ID: 83fb71e741b8
Revises: 8d40da51fdfd
Create Date: 2022-09-15 22:22:06.555070

"""
from alembic import op
import sqlalchemy as sa
import ormar


# revision identifiers, used by Alembic.
revision = '83fb71e741b8'
down_revision = '8d40da51fdfd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('npa_documents_complex_name_key', 'npa_documents', type_='unique')
    op.create_unique_constraint(None, 'npa_documents', ['eo_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'npa_documents', type_='unique')
    op.create_unique_constraint('npa_documents_complex_name_key', 'npa_documents', ['complex_name'])
    # ### end Alembic commands ###
